apiVersion: v1
kind: ServiceAccount
metadata:
  name: hasher

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hasher
rules:
  - apiGroups: ["apps"]
    verbs: ["patch", "get", "list"]
    resources:
      - deployments

  - apiGroups: [""]
    verbs: [ "patch", "get", "list" ]
    resources:
        - configmaps

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hasher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hasher
subjects:
  - kind: ServiceAccount
    name: hasher