# Dependency to database "postgresql"
# Set the unique name for secret for database
secretName: secret-database-to-integrity-sum
databaseDriver: postgres

postgresql:
  auth:
    # Authentication data to connect to the database, need to set
    postgresPassword: ""
    username: ""
    password: ""
    database: ""
    postgresqlDataDir: /bitnami/postgresql/data

  primary:
    initdb:
      scripts:
        # Set by the initdb script during initial container startup
        00_init_extensions.sh: |
          #!/bin/sh
          export PGPASSWORD=$POSTGRES_PASSWORD
          psql -w -d $POSTGRES_DB -U $POSTGRES_USER -c "
          CREATE TABLE IF NOT EXISTS hashfiles
          (
          id                BIGSERIAL PRIMARY KEY,
          file_name         VARCHAR NOT NULL,
          full_file_path    TEXT    NOT NULL,
          algorithm         VARCHAR NOT NULL,
          hash_sum          VARCHAR NOT NULL,
          name_deployment   TEXT,
          name_pod          TEXT,
          time_of_creation  VARCHAR (50),
          image_tag         TEXT
          );"

    # Enable security context
    podSecurityContext:
      enabled: false
      fsGroup: ""
    # Enable container security context
    containerSecurityContext:
      enabled: false
      runAsUser: "auto"
    service:
      ## PosgresSQL service type
      type: ClusterIP
      # clusterIP: None
      port: 5432

    persistence:
      # Enable PostgreSQL Primary data persistence using PVC
      enabled: true
      existingClaim: ""
      # mountPath: /bitnami/postgresql - default mountPath
      accessModes:
        - ReadWriteMany
      size: 5Gi

    #Enable security context
    readReplicas:
      podSecurityContext:
        enabled: false
        fsGroup: ""
      containerSecurityContext:
        enabled: false
        runAsUser: "auto"

    # Enable init container that changes the owner and group of the persistent volume
    volumePermissions:
      enabled: false
      securityContext:
        runAsUser: "auto"
